#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="yourls"

sanity_db mariadb
sanity_var SITE_URL "Site URL"
sanity_var ADMIN_USER "Admin User"
sanity_var ADMIN_PASS "Admin Password"

db_ready mariadb

### Check to see if this is a new install, if yes download Wordpress and other pieces...
if [ ! -f ${NGINX_WEBROOT}/yourls-loader.php ] ; then
   print_info "Potential New/Non Volatile Installation - Please wait while we setup.."
   cp -R /assets/install/* "${NGINX_WEBROOT}/"
  chown -R "${NGINX_USER}":"${NGINX_GROUP}" "${NGINX_WEBROOT}"
fi

### If running with /www/html or NGINX_WEBROOT mapped, then create persistent storage
### Storage redirection
if [ -d "/data" ]; then
    print_warn "Detected /data directory. Persistently saving config/uploads/themes/etc"
    config_file="/data/config"
    ln -sf "${config_file}" "${NGINX_WEBROOT}"/user/config.php
    if [ ! -d "/data/plugins" ]; then
        cp -R "${NGINX_WEBROOT}"/user/plugins /data
    fi
    rm -rf "${NGINX_WEBROOT}"/user/plugins
    ln -s /data/plugins "${NGINX_WEBROOT}"/user/plugins
    chown -R "${NGINX_USER}":"${NGINX_GROUP}" /data
else
    config_file="${NGINX_WEBROOT}/user/config.php"
fi

if [ ! -f "${config_file}" ] ; then
  cat <<EOL | silent sudo -u "${NGINX_USER}" tee "${config_file}"
<?php
define( 'YOURLS_DB_USER', '${DB_USER}' );
define( 'YOURLS_DB_PASS', '${DB_PASS}' );
define( 'YOURLS_DB_NAME', '${DB_NAME}' );
define( 'YOURLS_DB_HOST', '${DB_HOST}' );
define( 'YOURLS_DB_PREFIX', '${DB_PREFIX}' );
define( 'YOURLS_SITE', '${SITE_NAME}' );
define( 'YOURLS_HOURS_OFFSET', $(date +%z | sed "s|0||g") );
define( 'YOURLS_LANG', '' );
define( 'YOURLS_UNIQUE_URLS', true );
define( 'YOURLS_PRIVATE', true );
\$yourls_user_passwords = array(
       '${ADMIN_USER}' => '${ADMIN_PASS}',
        );
define( 'YOURLS_DEBUG', ${DEBUG} );
define( 'YOURLS_URL_CONVERT', 36 );
\$yourls_reserved_URL = array(
        'reserved',
);
EOL
else
    sudo -u "${NGINX_USER}" sed -i --follow-symlinks \
                                -e "/YOURLS_DB_USER/ c\define( 'YOURLS_DB_USER', '$DB_USER' );" \
                                -e "/YOURLS_DB_PASS/ c\define( 'YOURLS_DB_PASS', '$DB_PASS' );" \
                                -e "/YOURLS_DB_NAME/ c\define( 'YOURLS_DB_NAME', '$DB_NAME' );" \
                                -e "/YOURLS_DB_HOST/ c\define( 'YOURLS_DB_HOST', '$DB_HOST' );" \
                                -e "/YOURLS_DEBUG/ c\define( 'YOURLS_DEBUG', $DEBUG );" \
                                -e "/YOURLS_SITE/ c\define( 'YOURLS_SITE', '$SITE_NAME' );" \
                            "${config_file}"
fi

custom_files "${CONTAINER_CUSTOM_PATH}" "${NGINX_WEBROOT}" "${NGINX_USER}" "${NGINX_GROUP}"
custom_scripts

### Force Reset Permissions for Security
chown -R "${NGINX_USER}":"${NGINX_GROUP}" "${NGINX_WEBROOT}"
print_info "YOURLS ${YOURLS_VERSION} is ready to be accessed!"

liftoff
