#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="yourls"

sanity_db mariadb
sanity_var SITE_URL "Site URL"
sanity_var ADMIN_USER "Admin User"
sanity_var ADMIN_PASS "Admin Password"

db_ready mariadb

### Check to see if this is a new install, if yes download Wordpress and other pieces...
if [ ! -f ${NGINX_WEBROOT}/yourls-loader.php ] ; then
   print_info "Potential New/Non Volatile Installation - Please wait while we setup.."
   cp -R /assets/install/* "${NGINX_WEBROOT}/"
  chown -R "${NGINX_USER}":"${NGINX_GROUP}" "${NGINX_WEBROOT}"
fi

### If running with /www/html or NGINX_WEBROOT mapped, then create persistent storage
### Storage redirection
if [ -d "/data" ]; then
    print_warn "Detected /data directory. Persistently saving config/uploads/themes/etc"
    config_file="/data/config"
    ln -sf "${config_file}" "${NGINX_WEBROOT}"/user/config.php
    if [ ! -d "/data/plugins" ]; then
        cp -R "${NGINX_WEBROOT}"/user/plugins /data
    fi
    rm -rf "${NGINX_WEBROOT}"/user/plugins
    ln -s /data/plugins "${NGINX_WEBROOT}"/user/plugins
    chown -R "${NGINX_USER}":"${NGINX_GROUP}" /data
else
    config_file="${NGINX_WEBROOT}/user/config.php"
fi

if [ ! -f "${config_file}" ] ; then
  sudo -u ${NGINX_USER} cat > "${config_file}" <<EOL
<?php
define( 'YOURLS_DB_USER', '${DB_USER}' );
define( 'YOURLS_DB_PASS', '${DB_PASS}' );
define( 'YOURLS_DB_NAME', '${DB_NAME}' );
define( 'YOURLS_DB_HOST', '${DB_HOST}' );
define( 'YOURLS_DB_PREFIX', '${DB_PREFIX}' );
define( 'YOURLS_SITE', '${SITE_NAME}' );
define( 'YOURLS_HOURS_OFFSET', $(date +%z) | sed "s|0||g") );
define( 'YOURLS_LANG', '' );
define( 'YOURLS_UNIQUE_URLS', true );
define( 'YOURLS_PRIVATE', true );
\$yourls_user_passwords = array(
       '${ADMIN_USER}' => '${ADMIN_PASS}',
        );
define( 'YOURLS_DEBUG', ${DEBUG} );
define( 'YOURLS_URL_CONVERT', 36 );
\$yourls_reserved_URL = array(
        'reserved',
);
EOL
else
  sudo -u ${NGINX_USER} sed -i --follow-symlinks "/YOURLS_DB_USER/ c\define( 'YOURLS_DB_USER', '$DB_USER' );" "${config_file}"
  sudo -u ${NGINX_USER} sed -i --follow-symlinks "/YOURLS_DB_PASS/ c\define( 'YOURLS_DB_PASS', '$DB_PASS' );" "${config_file}"
  sudo -u ${NGINX_USER} sed -i --follow-symlinks "/YOURLS_DB_NAME/ c\define( 'YOURLS_DB_NAME', '$DB_NAME' );" "${config_file}"
  sudo -u ${NGINX_USER} sed -i --follow-symlinks "/YOURLS_DB_HOST/ c\define( 'YOURLS_DB_HOST', '$DB_HOST' );" "${config_file}"
  sudo -u ${NGINX_USER} sed -i --follow-symlinks "/YOURLS_DEBUG/ c\define( 'YOURLS_DEBUG', $DEBUG );" "${config_file}"
  sudo -u ${NGINX_USER} sed -i --follow-symlinks "/YOURLS_SITE/ c\define( 'YOURLS_SITE', '$SITE_NAME' );" "${config_file}"
fi

## Copy over any custom files overtop of source
if [ -d "/assets/custom" ]; then
    print_warn "Detected Custom Source - Copying over to application"
    cp -R /assets/custom/* "${NGINX_WEBROOT}"/
fi

## Execute Custom Scripts
if [ -d /assets/custom-scripts/ ] ; then
    print_warn "Found Custom Scripts to Execute"
    for f in $(find /assets/custom-scripts/ -name \*.sh -type f); do
        print_warn "Running Script ${f}"
        chmod +x "${f}"
        ${f}
    done
fi

### Force Reset Permissions for Security
chown -R "${NGINX_USER}":"${NGINX_GROUP}" "${NGINX_WEBROOT}"
print_info "YOURLS ${YOURLS_VERSION} is ready to be accessed!"

liftoff