version: '2.4'
services:

  yourls-app:
    image: tiredofit/yourls:latest
    container_name: yourls-app
    links:
      - yourls-db
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:yourls.hostname.com
      - traefik.port=80
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - traefik.backend=yourls-app
    volumes:
      - ./logs/:/www/logs
    environment:
      - VIRTUAL_HOST=yourls.hostname.com
      - VIRTUAL_NETWORK=proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=yourls.hostname.com
      - LETSENCRYPT_EMAIL=user@hostname.com

      - DB_HOST=yourls-db
      - DB_NAME=yourls
      - DB_USER=yourls
      - DB_PASS=userpassword

      - SITE_NAME=sitename.com
      - ADMIN_USER=admin
      - ADMIN_PASS=yourls

      - DEBUG=false
    networks:
      - proxy
      - services
    restart: always

  yourls-db:
    image: tiredofit/mariadb:latest
    container_name: yourls-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=yourls
      - DB_USER=yourls
      - DB_PASS=userpassword
    networks:
      - services
    restart: always

  yourls-db-backup:
    image: tiredofit/db-backup:latest
    container_name: yourls-db-backup
    links:
      - yourls-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - DB_HOST=yourls-db
      - DB_NAME=yourls
      - DB_USER=yourls
      - DB_PASS=userpassword
      - DB_TYPE=mariadb
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true

